//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : KuaiDiChaXun
//  @ File Name : LogoActivity.java
//  @ Date : 2015/10/11
//  @ Author : 
//
//



package com.ypf.kuaicha.activity;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;

import com.ypf.kuaicha.R;



public class LogoActivity extends Activity{
	Handler handler=new Handler();
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_logo);
		handler.postDelayed(new Runnable() {
			
			@Override
			public void run() {
				Intent intent=new Intent(LogoActivity.this, LoginActivity.class);
				startActivity(intent);
				finish();
			}
		}, 3000);
	}
}
