//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : KuaiDiChaXun
//  @ File Name : InformationEntity.java
//  @ Date : 2015/10/11
//  @ Author : 
//
//


package com.ypf.kuaicha.entity;

import com.lidroid.xutils.db.annotation.Id;

import java.io.Serializable;
import java.lang.reflect.Field;


/**
 * @author Administrator
 *
 */
public class Information implements Serializable  {

	public Information() {
		super();
	}
	@Id
	int id;
	public Result getResult() {
		return result;
	}
	public void setResult(Result result) {
		this.result = result;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String reason  ;
	public String resultcode  ;
	public  Result result;
	public void  setReason (String reason){this.reason=reason;}
	public String getReason (){return this.reason;}
	public void  setResultcode (String resultcode){this.resultcode=resultcode;}
	public String getResultcode (){return this.resultcode;}

	public String toString() {String s = "";Field[] arr = this.getClass().getFields();for (Field f : getClass().getFields()) {try {s += f.getName() + "=" + f.get(this) + "\n,";} catch (Exception e) {}}return getClass().getSimpleName() + "[" + (arr.length==0?s:s.substring(0, s.length() - 1)) + "]";}
}