//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : KuaiDiChaXun
//  @ File Name : UserEntity.java
//  @ Date : 2015/10/11
//  @ Author : 
//
//



package com.ypf.kuaicha.entity;

import com.lidroid.xutils.db.annotation.Finder;
import com.lidroid.xutils.db.annotation.Id;
import com.lidroid.xutils.db.annotation.Table;

import java.io.Serializable;
import java.util.List;

@Table(name="user")
public class User implements Serializable {
	@Id
	int id;
	String name;
	String password;
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public User() {
		super();
	}
	@Finder(valueColumn="id",targetColumn="userId")
	List<Result>list;
	public List<Result> getList() {
		return list;
	}
	public void setList(List<Result> list) {
		this.list = list;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
}
